[build]
runtime = "python-3.10"

[phases.install]
cmds = [
  "apt-get update && apt-get install -y python3-pip",
  "pip3 install -r requirements.txt"
]

[phases.start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT}"

